const data = {
    products: [
      {
        _id: '1',
        name: 'Nike Shoes',
        category: 'Chaussure pour Homme',
        image: '/images/1.jpg',
        price: 220,
        countInStock: 10,
        brand: 'Nike',
        rating: 3.5,
        numReviews: 10,
        description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus nobis modi aut architecto similique!',
        size:35,
      },
      {
        _id: '2',
        name: 'Adidas SHOES',
        category: 'Chaussure pour Homme',
        image: '/images/2.jpg',
        price: 200,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus nobis modi aut architecto similique!',
        size:45,
      },
      {
        _id: '3',
        name: 'Lacoste SHOES',
        category: 'Chaussure pour ENFANTS',
        image: '/images/3.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 2.8,
        numReviews: 17,
        description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus nobis modi aut architecto similique!',
        size:39,
      },
      {
        _id: '4',
        name: 'Nike SHOES',
        category: 'Chaussure pour Homme',
        image: '/images/4.jpg',
        price: 278,
        countInStock: 15,
        brand: 'Nike',
        rating: 1.5,
        numReviews: 14,
        description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus nobis modi aut architecto similique!',
        size:37,
      },
      {
        _id: '5',
        name: 'Puma SHOES',
        category: 'Chaussure pour FEMMES',
        image: '/images/5.jpg',
        price: 265,
        countInStock: 0,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus nobis modi aut architecto similique!',
        size:40,
      },
      {
        _id: '6',
        name: 'Adidas SHOES',
        category: 'Chaussure pour FEMMES',
        image: '/images/6.jpg',
        price: 239,
        countInStock: 5,
        brand: 'Adidas',
        rating: 3.5,
        numReviews: 15,
        description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus nobis modi aut architecto similique!',
        size:35,
      },
    ],
  };
  export default data;